import type { AccountRole } from '@/lib/auth/roles';
import type { InteractiveMessagePayload } from '@/lib/whatsapp/interactive';

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from '@/lib/whatsapp/interactive';

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, 'owner'>;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  name?: string;
  email?: string;
  company?: string;
  avatar_url?: string;
  /** Origem do lead, do objeto `referral` de um anúncio
   *  Click-to-WhatsApp. Gravada pelo webhook na PRIMEIRA mensagem e
   *  nunca sobrescrita (migrations 040/041). Somente leitura na
   *  interface: o valor vem da Meta, não do usuário. */
  ad_source_id?: string | null;
  /** 'ad' (anúncio pago) ou 'post' (publicação orgânica). */
  ad_source_type?: string | null;
  ad_source_url?: string | null;
  ad_headline?: string | null;
  /** Chave do clique, usada pela API de Conversões da Meta. */
  ctwa_clid?: string | null;
  /** Primeiro contato do lead. Distinto de `created_at`, que pode vir
   *  de importação. */
  first_seen_at?: string | null;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

export type NotificationType = 'conversation_assigned';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  title: string;
  body?: string;
  read_at?: string;
  created_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive';
export type MessageStatus =
  'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  phone_number_id: string;
  waba_id?: string;
  access_token: string;
  verify_token?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  created_at: string;
}

export type DealStatus = 'open' | 'won' | 'lost';

export interface Deal {
  id: string;
  user_id: string;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  /**
   * Tese do caso (migration 039). A coluna existia desde a 039 mas
   * nasceu órfã — nada a escrevia e este tipo não a declarava. A
   * automação de funil casa o negócio do contato POR TESE, então a
   * partir da migration 042 ela é preenchida na criação (copiada do
   * contato) e mantida pelo motor.
   */
  practice_area?: string | null;
  /**
   * Quando o negócio entrou na etapa atual (migration 042). Mantido
   * por gatilho de banco, portanto confiável mesmo quando a etapa é
   * trocada por um caminho que não passa pelo servidor.
   */
  stage_entered_at?: string | null;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
}

export type BroadcastStatus =
  'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus =
  'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | 'interactive_reply'
  // ---- Gatilhos de funil (migration 042) --------------------
  // Antes destes, o funil era um destino sem sensor: o motor sabia
  // criar um negócio e nada mais podia observá-lo. São o que torna
  // o pipeline reativo em vez de apenas gravável.
  /** Um negócio foi criado, por qualquer caminho. */
  | 'deal_created'
  /** Um negócio mudou de etapa — inclusive quando um humano
   *  arrastou o cartão no quadro. Permite encadear: mover para
   *  "Contrato Assinado" dispara a mensagem de boas-vindas. */
  | 'deal_stage_changed'
  /** Um negócio está parado na mesma etapa há N dias. Disparado
   *  pela varredura periódica, não por evento — depende do cron. */
  | 'deal_stalled'
  /** A tese do contato acabou de ser definida (NULL -> valor).
   *  É o gatilho da triagem: classificou, avança no funil. */
  | 'practice_area_set'
  /** Um documento enviado pelo passo `send_signature_request` voltou
   *  assinado — anunciado pelo webhook de entrada do ZapSign
   *  (migration 044). Não decide nada sozinho: o que acontece depois
   *  (mover o negócio, avisar o time) é a automação que o usuário
   *  monta a partir daqui, mesmo desenho de `practice_area_set`. */
  | 'document_signed';

export type AutomationStepType =
  | 'send_message'
  | 'send_buttons'
  | 'send_list'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  /** A peça que faltava: mover o negócio do contato para outra
   *  etapa do funil. Sem ela o motor criava o negócio na etapa
   *  inicial e nunca mais o tocava (migration 042). */
  | 'move_deal_stage'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation'
  /** Gera um documento no ZapSign a partir de um modelo e, por padrão,
   *  manda o link de assinatura pelo WhatsApp do escritório. Ver
   *  SendSignatureRequestStepConfig e migration 044. */
  | 'send_signature_request';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  match_type: 'exact' | 'contains';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

/**
 * Filtro do gatilho `deal_stage_changed`. Todos os campos são
 * opcionais e se combinam por E: vazio significa "qualquer", não
 * "nenhum". Sem filtro nenhum, a automação reage a toda passagem de
 * etapa do funil — raramente o que se quer, mas é a leitura honesta
 * de um filtro em branco.
 */
export interface DealStageChangedTriggerConfig {
  pipeline_id?: string;
  /** Dispara só quando o negócio ENTRA nesta etapa. */
  to_stage_id?: string;
  /** Dispara só quando o negócio SAI desta etapa. */
  from_stage_id?: string;
}

export interface DealCreatedTriggerConfig {
  pipeline_id?: string;
}

/**
 * Filtro do gatilho `deal_stalled`. Diferente dos outros, aqui
 * `stage_id` e `days` são OBRIGATÓRIOS: a varredura periódica
 * pergunta ao banco "quem está parado nesta etapa há mais de N dias",
 * e nenhuma das duas metades tem padrão razoável. Vigiar o funil
 * inteiro seria uma varredura cara com significado ambíguo.
 */
export interface DealStalledTriggerConfig {
  stage_id: string;
  pipeline_id?: string;
  /** Dias parado na etapa antes de disparar. */
  days: number;
}

/**
 * Filtro do gatilho `practice_area_set`. Lista vazia ou ausente =
 * qualquer tese dispara.
 */
export interface PracticeAreaSetTriggerConfig {
  practice_areas?: string[];
}

/**
 * Filtro do gatilho `document_signed`. Vazio/ausente = qualquer modelo
 * dispara, mesma convenção de `practice_area_set`.
 */
export interface DocumentSignedTriggerConfig {
  template_token?: string;
}

/**
 * Uma linha de `zapsign_documents` (migration 044): um documento
 * enviado para assinatura. Escrita é exclusiva do service-role — o
 * passo `send_signature_request` cria com `pending`, o webhook de
 * entrada fecha em `signed`/`refused`. A UI só lê.
 */
export interface ZapsignDocument {
  id: string;
  account_id: string;
  contact_id: string;
  deal_id: string | null;
  automation_id: string | null;
  /**
   * Token do DOCUMENTO no ZapSign, não do modelo. NULL enquanto a
   * criação não foi confirmada — a linha é gravada antes da chamada, e o
   * `id` viaja como `external_id` para o webhook conseguir reencontrá-la
   * se a resposta se perder. Ver migration 044.
   */
  zapsign_token: string | null;
  template_token: string;
  name: string;
  status: 'pending' | 'signed' | 'refused';
  sign_url: string | null;
  signed_at: string | null;
  created_at: string;
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | DealStageChangedTriggerConfig
  | DealCreatedTriggerConfig
  | DealStalledTriggerConfig
  | PracticeAreaSetTriggerConfig
  | DocumentSignedTriggerConfig
  | Record<string, unknown>;

export interface SendMessageStepConfig {
  text: string;
}

/**
 * `send_buttons` / `send_list` step configs carry the full interactive
 * payload (same shape stored on messages + quick replies). `kind` is
 * implied by the step_type but kept on the payload for a uniform shape.
 */
export type SendButtonsStepConfig = InteractiveMessagePayload;
export type SendListStepConfig = InteractiveMessagePayload;

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

/**
 * Como o passo `move_deal_stage` escolhe QUAL negócio mover, quando o
 * contato tem mais de um. Um lead de BPC e um de aposentadoria são
 * casos distintos que não podem se atropelar no funil.
 *
 * - `auto` (padrão): usa o negócio que veio no contexto do gatilho
 *   quando existe (gatilhos de funil já trazem um); senão cai para
 *   `practice_area`; senão para `latest_open`. É a escolha certa em
 *   praticamente todos os casos.
 * - `practice_area`: casa pela tese do negócio, comparando com a tese
 *   do contexto ou a do contato. Ignora negócios de outra tese.
 * - `latest_open`: o negócio aberto mais recente do contato,
 *   independente de tese.
 * - `context`: SÓ o negócio que disparou o gatilho. Se não houver,
 *   o passo não faz nada — útil quando mover o negócio errado é pior
 *   que não mover nenhum.
 */
export type DealMatchMode =
  'auto' | 'practice_area' | 'latest_open' | 'context';

export interface MoveDealStageStepConfig {
  pipeline_id: string;
  /** Etapa de destino. */
  stage_id: string;
  match_by?: DealMatchMode;
  /**
   * Se o contato não tem negócio que case, cria um já na etapa de
   * destino. É o que impede um lead atendido de ficar fora do funil.
   * Ignorado quando `match_by` é `context`.
   */
  create_if_missing?: boolean;
  /** Título do negócio criado. Aceita `{{ ... }}`. Só usado com `create_if_missing`. */
  title?: string;
  /**
   * Muda também o status ao mover — para etapas terminais como
   * "Contrato Assinado" (won) ou "Perdido" (lost). Ausente = status
   * intocado.
   */
  set_status?: DealStatus;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  'contact_field' | 'tag_presence' | 'message_content' | 'time_of_day';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

/**
 * Passo `send_signature_request` (migration 044). Gera um documento no
 * ZapSign a partir de um MODELO já cadastrado lá (não upload de PDF) e,
 * quando `send_via_whatsapp`, manda o link de assinatura pelo WhatsApp
 * do escritório dentro do mesmo passo — sem depender de um mecanismo
 * novo de variável entre passos.
 */
export interface SendSignatureRequestStepConfig {
  /** Token do MODELO no ZapSign (de GET /api/v1/templates/), não do documento. */
  template_token: string;
  /**
   * Modelos ANEXADOS ao mesmo envelope do principal, na ordem em que
   * devem aparecer. Contrato + procuracao num link so: o signatario
   * preenche o formulario uma vez e assina os dois de uma vez, em vez
   * de receber dois links e repetir a qualificacao inteira.
   *
   * Ausente ou vazio = envelope com um documento so, que e o
   * comportamento anterior.
   */
  extra_template_tokens?: string[];
  /** Nome do documento exibido no ZapSign. Aceita `{{ vars.* }}` / `{{ message.text }}`. */
  document_name: string;
  /** Variáveis do modelo: nome-da-variável -> valor. Valores aceitam interpolação. */
  variables?: Record<string, string>;
  send_via_whatsapp: boolean;
  /**
   * Manda o signatário ao formulário do MODELO antes de assinar, para
   * completar o que `variables` não preencheu (ZapSign:
   * `signer_has_incomplete_fields`). É como se colhe CPF, RG e endereço
   * sem um formulário externo: o dado nasce dentro do documento, com a
   * validação de tipo que o modelo define. Ausente = comportamento
   * anterior, em que o campo não é enviado.
   */
  signer_has_incomplete_fields?: boolean;
  /**
   * Texto da mensagem de WhatsApp. Obrigatório quando `send_via_whatsapp`
   * é true. Use o token literal `{{signer_url}}` onde o link deve entrar;
   * também aceita `{{ vars.* }}` / `{{ message.text }}`.
   */
  message_text?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendButtonsStepConfig
  | SendListStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | MoveDealStageStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | SendSignatureRequestStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

export type QuickReplyKind = 'text' | 'interactive';

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  kind: QuickReplyKind;
  /** Set when `kind === 'text'`. */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  created_at: string;
  updated_at: string;
}
